- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20240518012440209900000012.chy648q6g6nn.us-east-1.rds.amazonaws.com" 
    login_user: "admin"
    login_password: "admin12345"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: '^localhost', replace: "terraform-20240518012440209900000012.chy648q6g6nn.us-east-1.rds.amazonaws.com" }
    - { regexp: '^username_here', replace: "admin" }
    - { regexp: '^database_name_here', replace: "wordpressdb" }
    - { regexp: '^password_here', replace: "admin12345" }
